### ISSUE TITLE
Outdated value in ZFS

### ISSUE THREAD

**Issue by ktoczyski** [mmatuska/zfs-stats#5]
Hi,

I new FreeBSD and ZFS is missing value "kstat.zfs.misc.arcstats.recycle_miss".

```
sysctl -a kstat.zfs.misc.arcstats.recycle_miss
sysctl: unknown oid 'kstat.zfs.misc.arcstats.recycle_miss'
```

I check it on:

12.1
12.0
11.1

Your script through it have error:

```
ARC Misc:
	Deleted:				2381299
Use of uninitialized value in printf at ./zfs-stats line 337.
	Recycle Misses:				
	Mutex Misses:				1009
	Evict Skips:				0
```

Workaround is remove or comment line: 333 and 337.

Could you update your script?

**Comment by stesser** [comment]
This issue has been fixed in the FreeBSD ports SVN (revision 551638) on 2020-10-07.
A few days ago I have applied the fix to this repository and tagged the new version as 1.3.1.
